export default {
  siteName: 'Portal3-ADMIN',
  currentUser: 'currentAdmin',
  language: 'languageAdmin',
  section: 'sectionAdmin',
  success: 'success',
  error: 'error',
  uploadMaxsize: 5,
  human: 'human',
  conference: 'conference',
  business: 'business',
  upcoming: 'upcoming',
  previous: 'previous',
  event: 'event',
  course: 'course',
}
