export default {
  siteName: 'Portal3-ADMIN',
  currentUser: 'currentAdmin',
  language: 'languageAdmin',
  section: 'sectionAdmin',
  success: 'success',
  error: 'error',
  uploadMaxsize: 5,
  human: 'human',
  conference: 'conference',
  business: 'business',
  upcoming: 'upcoming',
  previous: 'previous',
  event: 'event',
  course: 'course',

  male: 'M',
  female: 'F',

  PHONE_PREFIX_BAHRAIN: "+973",
  PHONE_PREFIX_KUWAIT: "+965",
  PHONE_PREFIX_OMAN: "+968",
  PHONE_PREFIX_QATAR: "+974",
  PHONE_PREFIX_SAUDI_ARABIA: "+966",
  PHONE_PREFIX_UAE: "+971",
}
